practice
HeXA-UNIST/hexa-homepage-2023-backend pull request #14
Opened 2023-06-29 11:42 UTC by HyunsuYEE

practice - assignment2

2023-07-06 14:39 UTC, SYChoi requested changes

2023-07-06 14:39 UTC, SYChoi commented on build.gradle
> +implementation 'com.github.jasontypescodes:mn-config-based-auth:2.2.0'
dependency 추가된 것 삭제 요망

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-core/build.gradle
> +    implementation 'com.github.jasontypescodes:mn-config-based-auth:2.2.0'
dependency 추가된 것 삭제 요망

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-domain/build.gradle
> +    implementation 'com.github.jasontypescodes:mn-config-based-auth:2.2.0'
dependency 추가된 것 삭제 요망

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-domain/src/main/java/pro/hexa/backend/config/JpaQueryFactoryConfig.java
> +    private EntityManager entityManager;
EntityManager의 경우 기본적으로 하나 bean으로 등록되어있기 때문에 굳이 이렇게 선언할 필요도 없고, 그렇기 때문에 아래 queryFactory Bean 등록할 때 parameter로 EntityManager 넣을 때 자동으로 주입이 되었음. 삭제 필요.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-domain/src/main/java/pro/hexa/backend/domain/Board/domain/Board.java
> +//    public void a(){
나중에 merge 할 때는 이런 연습용 주석은 모두 삭제를 해야함.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-domain/src/main/java/pro/hexa/backend/domain/project_member/domain/ProjectMember.java
> +    private String id; // 왜 string이노
project member의 id 값인데 잘못 만들어진듯? 그냥 Long으로 변경해주면 될 것 같음.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-domain/src/main/java/pro/hexa/backend/domain/user/repository/UserRepository.java
> +import java.util.List;
사용하지 않는 import의 경우 없애는 것이 좋은데, 이건 intelliJ에 자동으로 commit 할 때 optimize import 해주는 옵션이 있음. 옵션 변경을 해보도록 하자.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-domain/src/main/java/pro/hexa/backend/domain/user/repository/UserRepositoryImpl.java
> +import static pro.hexa.backend.domain.user.domain.QUser.user;
static 변수를 이렇게 가져오는것도 괜찮긴 하지만 queryDSL 사용할 때 그냥 Q 변수 가져오고 하위에 있는 user는 지역 변수로 쓰는게 좀 더 일반적임. 아래에서 예시로 따로 보여주겠음.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-domain/src/main/java/pro/hexa/backend/domain/user/repository/UserRepositoryImpl.java
> +
이 함수의 경우 구현을 아래와 같이 하면 좋음.
```
QUser user = QUser.user;
return queryFactory.selectFrom(user)
    .where(
        user.name.eq(requestedName),
        user.email.eq(requestedEmail)
    ).fetchOne();
```

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/build.gradle
> +    implementation 'com.github.jasontypescodes:mn-config-based-auth:2.2.0'
삭제 필요

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-domain/src/main/java/pro/hexa/backend/domain/user/repository/UserRepositoryImpl.java
> +
이유는 where 아래에 조건이 어차피 콤마로 구분해 넣어도 모두 and로 자동으로 들어가고, 계속해서 and를 사용하면 끊임없이 조건이 많아질 때 괄호가 많아지므로 읽기 힘들어지는 문제가 발생함.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/common/config/security/UserDetailsServiceImpl.java
> +public class UserDetailsServiceImpl implements UserDetailsService {
사용 안하게 된 것은 삭제를 하도록 하자

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/common/config/security/WebSecurityConfig.java
> +//    @Bean
다시 살려두자....

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/controller/UserController.java
> +import pro.hexa.backend.main.api.domain.login.dto.*;
import 자동으로 최대한 묶지 않도록 자동으로 묶는 개수를 999로 바꿔주는 intelliJ 설정 변경을 해주도록 하자.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/controller/UserController.java
>      @Operation(description = "회원가입")
field 변수 선언과 그 다음 함수 혹은 다른 요소 간에 항상 한칸 공백을 둬서 구분되도록 해주자.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/controller/UserController.java
균일하게 1칸으로 공백을 주자.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/controller/UserController.java
> +    }
공백 없는 곳은 없게 하고.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/dto/EmailRequestDto.java
> +    private String email;
이런 것도 Schema 어노테이션을 같이 달아서 swagger에 다 보이게 하는게 좋음.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/dto/EmailRequestDto.java
> +@Data
Data 어노테이션은 잘 달지 않음... 여기에 좀 무시무시한 것들이 많아서 안쓰는게 좋음. 자세한 사항은 꼭 검색해서 알아보기 바람.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/common/config/security/CustomAuthenticationProvider.java
> +@Log4j2
요거보단 @Slf4j 를 달아두는게 더 나음. 그게 더 일반적인 interface에 해당하는 어노테이션이라.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/common/config/security/CustomAuthenticationProvider.java
> +}
파일 올리기 전에 ctrl + alt + l 한번 눌러보면 알아서 intellij가 정렬을 싹 해줄것.
다만 꼭 editor 설정에서 tabsize를 모두 4로 조정해두고 할것.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +    @Transactional
수정이 없는 함수의 경우 @Transactional을 따로 안붙이기 위해 위쪽에 Class 전체에 readOnly Transactional을 붙여뒀음.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        String userName = request.getName();
여러번 사용하는 변수가 아니라면 굳이 이렇게 변수로 다시 뽑을 이유가 없음.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        User foundUser = userRepository.findByNameAndEmail(userName, userEmail);
repository에 넣기 전에 요청이 올바른지 validation을 먼저 해보는게 좋음. 이상한 값이나 문제 있는 것들이 DB 쿼리에 들어가면 안되니까.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        if(foundUser == null){
이렇게 예외처리하는 방법도 있지만 Optional로 애초에 찾아오는 결과값을 처리해놓고 가져왔으면 좀 더 예외처리가 예뻤을 것으로 보임.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +            throw new BadRequestException(BadRequestType.CANNOT_FIND_USER);
이 경우에는 BadRequest보다는 DataNotFound라고 보는게 맞음.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        if(emailSender.getAuthenticationNumbers() != userAuthenticationNumbers){
애초에 DB에서 찾아오기 전에 이걸 먼저 했어야하지 않을까?

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +    public String findUserPasswordFirst(UserFindPasswordFirstRequestDto request){
좀 더 이름을 서비스에 맞는... 하는 일에 해당하는 네이밍을 하기 바람. 기획을 모르면 뭘 하고 싶은 함수인지 전혀 알 수 없음.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +    public String findUserPasswordFirst(UserFindPasswordFirstRequestDto request){
예시로 들자면 findEmailWithUserIdToChangePassword 같은 식

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +    @Transactional
함수 하나 끝나면 한줄 비워서 가독성을 높여보자.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        if(foundUser.get() == null){
optional로 foundUser를 가져왔으면 .get을 해서 이렇게 하기보단.....
`userRepository.findById(userId).orElseThrow(() -> new BadRequestException(BadRequestType.CANNOT_FIND_USER));` 같은 식이 될듯.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        if(foundUser == null){
요런 null check 모두 가져올 때 optional로 가져와서 optional에서 처리하는 연습을 해보자.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +    public String findUserPasswordSecond(UserFindPasswordSecondRequestDto request){
이거 함수가 완전 아이디 찾기 할 때랑 동일해보이지 않음? 그냥 통일 시켜도 될거같음.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +    @Transactional
얘도 값 읽기 뿐이니 Transactional은 떼어내자.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +    @Transactional
DB 값 수정 없으니 Transactional 제거.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        User deletedUser = userRepository.getById(request.getId());
delete 후 새로 생성하는 방식은 전혀 맞지 않으므로 정말 password만 변경하는 방식으로 다시 만들어보자.

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        return true;
이렇게 boolean만 돌려줄바엔 아무것도 return 안하는 void 함수가 더 나음

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/AbstactEmailSender.java
> +public abstract class EmailSender {
같이 다시 만들어보도록 하자 ㅋㅋ....

2023-07-06 14:39 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/RedisUtil.java
> +public class RedisUtil {
임시 저장소를 위해 Redis를 사용한 것 같은데 우린 굳이 Redis까지 사용하기엔 너희가 너무 빠듯할테니 일단 없이 해보는걸로 하자.

2023-07-06 14:40 UTC, eumppe reviewed
히히

2023-07-06 14:40 UTC, eumppe commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        if(emailSender.getAuthenticationNumbers() != userAuthenticationNumbers){
authenticationCode를 emailSender에서 가져올 것이 아니라 redis에 저장했던 것을 가져오도록 해야해요. 아래에 있는 코드들도 마찬가지.

2023-07-07 04:17 UTC, HyunsuYEE commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/AbstactEmailSender.java
> +        this.AuthenticationNumbers = authKey;
이렇게 AuthenticationNumbers를 복사를 해두면 Redis를 쓴 이유가 없다

2023-07-07 04:17 UTC, HyunsuYEE commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/common/config/security/WebSecurityConfig.java
> +//    @Bean
이게 근데 죽여논 게 아니라 원래 없던 코드여서 주석처리를 해둔 것 같아요. 원래 CustomAutehnticationProvider라는 클래스는 없는데 제가 이것저것 하면서 만들었다가 로그인이 이미 구현된거라는 걸 깨닫고 주석처리 해둔 것 같아요. 주석처리를 빼는 게 맞나요.?

2023-07-07 04:17 UTC, HyunsuYEE commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/controller/UserController.java
> +import pro.hexa.backend.main.api.domain.login.dto.*;
file -> setting -> java -> class count to use import with * 를 999로 바꾸는 건가요?

2023-07-20 13:33 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        userRepository.findById(userId).orElseThrow(DataNotFoundException::new);
userRepository 조회해서 쓰지 않을거면 왜 조회해본걸까....?

2023-07-20 13:35 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        List<String> authKeys = authenticationNumbers.stream().map(AuthenticationNumber::getRandomAuthenticationNumbers).collect(Collectors.toList());
함수 하나 쓰고 . 찍을때마다 줄 바꿈을 해줘... .그래야 읽기 편해 stream은 특히나 더

2023-07-20 13:37 UTC, SYChoi commented on hexa-homepage-backend-main-app/src/main/java/pro/hexa/backend/main/api/domain/login/service/UserService.java
> +        user.orElseThrow(DataNotFoundException::new);
굳이 따로 아래에서 .orElseThrow할 것 없이 위에서 바로 붙여서 orElseThrow까지 하고 user는 Optional이 아닌 그냥 User 형태로 받아오면 됐을듯

2023-10-01 00:53 UTC, closed without merging